#!/bin/sh
echo "Starting app in $NODE_ENV mode"
if [ "$NODE_ENV" = "development" ] 
then
	DEBUG=main,routes node --harmony main.js
elif [ "$NODE_ENV" = "staging" ] 
then
	DEBUG=main,routes node --harmony main.js
else 
  	node --harmony main.js
fi
